version: '3.7'
services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 8888:80
    depends_on:
      - fileshares-account-service
      - fileshares-files-service
      - fileshares-social-service
      - fileshares-archiver-service

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    build:
      context: .
      dockerfile: rabbitMQ.Dockerfile


  fileshares-account-service:
    image: ghcr.io/eduardman/fileshares-account:latest
    depends_on:
      - fileshares-account-db
      - rabbitmq

  fileshares-files-service:
    image: ghcr.io/eduardman/fileshares-files:latest
    depends_on:
      - fileshares-files-db
      - rabbitmq

  fileshares-social-service:
    image: ghcr.io/eduardman/fileshares-social:latest
    depends_on:
      - fileshares-social-db
      - rabbitmq

  fileshares-archiver-service:
    image: ghcr.io/eduardman/fileshares-archiver:latest
    depends_on:
      - fileshares-archiver-db
      - rabbitmq

  jaeger-ui:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686
    depends_on:
      - fileshares-account-service
      - fileshares-files-service
      - fileshares-social-service
      - fileshares-archiver-service


  fileshares-account-db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=fileshares_account
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  fileshares-files-db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=fileshares_files
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  fileshares-social-db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=fileshares_social
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  fileshares-archiver-db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=fileshares_archiver
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password