application:
  queues:
    deleted-files: files-deleted-social-queue

spring:
  datasource:
    url: jdbc:postgresql://fileshares-social-db:5432/fileshares_social
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update