application:
  queues:
    deleted-files: files-deleted-queue

spring:
  datasource:
    url: jdbc:postgresql://localhost:6870/fileshares_social
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082