POST http://localhost:8888/api/social/storage
Authorization: Bearer {{auth_token}}
Content-Type: application/json

[
  {
    "fileUUID": "{{fileUUID}}",
    "compressLevel": 5
  }
]

###

POST http://localhost:8888/api/social/getPublicLink?fileUUID={{fileUUID}}
Authorization: Bearer {{auth_token}}

> {%
client.global.set("shareLink", response.body)
%}

###

GET http://localhost:8888/api/social/getAllOwnerFiles
Authorization: Bearer {{auth_token}}

###

GET http://localhost:8888/api/social/getAllUserFiles?ownerId=1
Authorization: Bearer {{auth_token}}

###

POST http://localhost:8888/api/social/access/changeAccess
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "filesUUID": [
    "{{fileUUID}}"
  ],
  "access": "PUBLIC"
}

###

POST http://localhost:8888/api/social/access/changeAccess
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "filesUUID": [
    "{{fileUUID}}"
  ],
  "access": "PRIVATE"
}

###

POST http://localhost:8888/api/social/attitude/like?fileUUID={{fileUUID}}
Authorization: Bearer {{auth_token}}

###

POST http://localhost:8888/api/social/attitude/dislike?fileUUID={{fileUUID}}
Authorization: Bearer {{auth_token}}

###

POST http://localhost:8888/api/social/attitude/comment?fileUUID={{fileUUID}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "text": "It's a great file. Thanks!"
}

> {%
client.global.set("commentId", response.body)
%}

###

POST http://localhost:8888/api/social/attitude/removeComment?commentId={{commentId}}
Authorization: Bearer {{auth_token}}