POST http://localhost:8888/api/social/storage
Authorization: Bearer {{auth_token}}
Content-Type: application/json

[
  {
    "fileUUID": "{{fileUUID}}",
    "compressLevel": 5
  }
]

###

POST http://localhost:8888/api/social/getPublicLink?fileUUID={{fileUUID}}
Authorization: Bearer {{auth_token}}

###

GET http://localhost:8888/api/social/getAllOwnerFiles
Authorization: Bearer {{auth_token}}

###

GET http://localhost:8888/api/social/getAllUserFiles?ownerId=1
Authorization: Bearer {{auth_token}}

###

POST http://localhost:8888/api/social/access/changeAccess
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "filesUUID": [
    "{{fileUUID}}"
  ],
  "access": "PUBLIC"
}

###

POST http://localhost:8888/api/social/access/changeAccess
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "filesUUID": [
    "{{fileUUID}}"
  ],
  "access": "PRIVATE"
}